/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api.verify-payment'
import { Route as ApiProvisionAccountRouteImport } from './routes/api.provision-account'
import { Route as ApiNotifyNewPurchaseRouteImport } from './routes/api.notify-new-purchase'
import { Route as ApiInitializePaymentRouteImport } from './routes/api.initialize-payment'
import { Route as ApiDeliverAccountRouteImport } from './routes/api.deliver-account'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as ApiPublicPushEventRouteImport } from './routes/api.public.push-event'
import { Route as AuthenticatedCommunitySlugRouteImport } from './routes/_authenticated/community.$slug'
import { Route as ApiPublicCronSyncEquityRouteImport } from './routes/api.public.cron.sync-equity'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionAccountRoute = ApiProvisionAccountRouteImport.update({
  id: '/api/provision-account',
  path: '/api/provision-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyNewPurchaseRoute = ApiNotifyNewPurchaseRouteImport.update({
  id: '/api/notify-new-purchase',
  path: '/api/notify-new-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInitializePaymentRoute = ApiInitializePaymentRouteImport.update({
  id: '/api/initialize-payment',
  path: '/api/initialize-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliverAccountRoute = ApiDeliverAccountRouteImport.update({
  id: '/api/deliver-account',
  path: '/api/deliver-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const ApiPublicPushEventRoute = ApiPublicPushEventRouteImport.update({
  id: '/api/public/push-event',
  path: '/api/public/push-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunitySlugRoute =
  AuthenticatedCommunitySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const ApiPublicCronSyncEquityRoute = ApiPublicCronSyncEquityRouteImport.update({
  id: '/api/public/cron/sync-equity',
  path: '/api/public/cron/sync-equity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/rules': typeof RulesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agreement': typeof AgreementRoute
  '/buy': typeof BuyRoute
  '/rules': typeof RulesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/deliver-account': typeof ApiDeliverAccountRoute
  '/api/initialize-payment': typeof ApiInitializePaymentRoute
  '/api/notify-new-purchase': typeof ApiNotifyNewPurchaseRoute
  '/api/provision-account': typeof ApiProvisionAccountRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/_authenticated/community/$slug': typeof AuthenticatedCommunitySlugRoute
  '/api/public/push-event': typeof ApiPublicPushEventRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/api/public/cron/sync-equity': typeof ApiPublicCronSyncEquityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreement'
    | '/buy'
    | '/rules'
    | '/admin'
    | '/affiliate'
    | '/community'
    | '/dashboard'
    | '/profile'
    | '/api/deliver-account'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/provision-account'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/community/$slug'
    | '/api/public/push-event'
    | '/community/'
    | '/api/public/cron/sync-equity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/buy'
    | '/rules'
    | '/admin'
    | '/affiliate'
    | '/dashboard'
    | '/profile'
    | '/api/deliver-account'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/provision-account'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/community/$slug'
    | '/api/public/push-event'
    | '/community'
    | '/api/public/cron/sync-equity'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agreement'
    | '/buy'
    | '/rules'
    | '/_authenticated/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/api/deliver-account'
    | '/api/initialize-payment'
    | '/api/notify-new-purchase'
    | '/api/provision-account'
    | '/api/verify-payment'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/payment/callback'
    | '/_authenticated/community/$slug'
    | '/api/public/push-event'
    | '/_authenticated/community/'
    | '/api/public/cron/sync-equity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgreementRoute: typeof AgreementRoute
  BuyRoute: typeof BuyRoute
  RulesRoute: typeof RulesRoute
  ApiDeliverAccountRoute: typeof ApiDeliverAccountRoute
  ApiInitializePaymentRoute: typeof ApiInitializePaymentRoute
  ApiNotifyNewPurchaseRoute: typeof ApiNotifyNewPurchaseRoute
  ApiProvisionAccountRoute: typeof ApiProvisionAccountRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ApiPublicPushEventRoute: typeof ApiPublicPushEventRoute
  ApiPublicCronSyncEquityRoute: typeof ApiPublicCronSyncEquityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision-account': {
      id: '/api/provision-account'
      path: '/api/provision-account'
      fullPath: '/api/provision-account'
      preLoaderRoute: typeof ApiProvisionAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-new-purchase': {
      id: '/api/notify-new-purchase'
      path: '/api/notify-new-purchase'
      fullPath: '/api/notify-new-purchase'
      preLoaderRoute: typeof ApiNotifyNewPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/initialize-payment': {
      id: '/api/initialize-payment'
      path: '/api/initialize-payment'
      fullPath: '/api/initialize-payment'
      preLoaderRoute: typeof ApiInitializePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deliver-account': {
      id: '/api/deliver-account'
      path: '/api/deliver-account'
      fullPath: '/api/deliver-account'
      preLoaderRoute: typeof ApiDeliverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/api/public/push-event': {
      id: '/api/public/push-event'
      path: '/api/public/push-event'
      fullPath: '/api/public/push-event'
      preLoaderRoute: typeof ApiPublicPushEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/$slug': {
      id: '/_authenticated/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof AuthenticatedCommunitySlugRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/api/public/cron/sync-equity': {
      id: '/api/public/cron/sync-equity'
      path: '/api/public/cron/sync-equity'
      fullPath: '/api/public/cron/sync-equity'
      preLoaderRoute: typeof ApiPublicCronSyncEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunitySlugRoute: typeof AuthenticatedCommunitySlugRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunitySlugRoute: AuthenticatedCommunitySlugRoute,
    AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgreementRoute: AgreementRoute,
  BuyRoute: BuyRoute,
  RulesRoute: RulesRoute,
  ApiDeliverAccountRoute: ApiDeliverAccountRoute,
  ApiInitializePaymentRoute: ApiInitializePaymentRoute,
  ApiNotifyNewPurchaseRoute: ApiNotifyNewPurchaseRoute,
  ApiProvisionAccountRoute: ApiProvisionAccountRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ApiPublicPushEventRoute: ApiPublicPushEventRoute,
  ApiPublicCronSyncEquityRoute: ApiPublicCronSyncEquityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
